### ISSUE TITLE
Cannot set shardKey when deleting vectors

### ISSUE THREAD

**Issue by forestwanglin** [qdrant/java-client#20]
For some reason, I want to delete the vectors.

Here is the code.

```java
 qdrantClient.deleteVectorsAsync(collectionName, vectors, ids).get()
```

I get below error message.
```
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Wrong input: No shards found for shard key
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-02-05 13:16:38.540 [] ERROR i.q.c.QdrantClient[2628] -- Delete vectors operation failed
```

But I didn't find how to set shardKey. Anyone know it?

**Comment by Anush008** [comment]
Hi @forestwanglin. We indeed missed this param in the vector delete overloads. I'll put up a patch for this soon.
Thank you.

**Comment by forestwanglin** [comment]
Thanks a lot, I will update when you patch it.
