### ISSUE TITLE
Default demo does not work

### ISSUE THREAD

**Issue by KlausSchaefers** [qdrant/java-client#32]
I am following the example in the readme.md running against a local docker instance of Quadrant. My code throws an exception as soon as I fire a command, e.g. create a collection. I see the following message:

```trace

java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]

	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
	at qdrant.CrudTest.createCollection(CrudTest.java:31)


...

Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 000012040000000000000400100000000500004000000601000000
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1308)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1378)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)

```

My code looks like 
```java

 QdrantGrpcClient lowLevelClient = QdrantGrpcClient
                .newBuilder("localhost")
                .build();
 client = new QdrantClient(lowLevelClient);

 Collections.VectorParams params = Collections.VectorParams
                .newBuilder()
                .setDistance(Collections.Distance.Cosine)
                .setSize(dim)
                .build();

Collections.CollectionOperationResponse response = client
                .createCollectionAsync(name, params)
                .get();
```

**Comment by Anush008** [comment]
Is Qdrant accessible at port 6334?

```
docker run -p 6334:6334 qdrant/Qdrant
```

**Comment by KlausSchaefers** [comment]
I have started the container with this command

```sh
docker run -p 6333:6333 -p 6334:6334 \
    -v $(pwd)/qdrant_storage:/qdrant/storage:z \
    qdrant/qdrant
```

**Comment by KlausSchaefers** [comment]
I see the following output 
```
2024-04-25T07:20:42.886031Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
2024-04-25T07:20:42.954644Z  INFO qdrant: Distributed mode disabled    
2024-04-25T07:20:42.954715Z  INFO qdrant: Telemetry reporting enabled, id: 8743b3dd-e56e-42fa-a0fe-f8fe2fa1b61b    
2024-04-25T07:20:42.958037Z  INFO qdrant::actix: TLS disabled for REST API    
2024-04-25T07:20:42.958244Z  INFO qdrant::actix: Qdrant HTTP listening on 6333    
2024-04-25T07:20:42.958270Z  INFO actix_server::builder: Starting 7 workers
2024-04-25T07:20:42.958280Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
2024-04-25T07:20:42.973731Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334    
2024-04-25T07:20:42.973752Z  INFO qdrant::tonic: TLS disabled for gRPC API 
```

**Comment by Anush008** [comment]
`useTls` defaults to `true`. Since you've not configured it locally, the error.

You can instantiate the client like so:
```java
import io.qdrant.client.QdrantClient;
import io.qdrant.client.QdrantGrpcClient;

QdrantClient client = new QdrantClient(
    QdrantGrpcClient.newBuilder("localhost", 6334, false).build());
```

**Comment by KlausSchaefers** [comment]
This might be related to some local proxies that are running. If I check the RNV vars I can see

```
https_proxy=http://proxy.server.xyx:3128
http_proxy=http://proxy.server.xyx:3128
```

For local http calls I usually have to overwrite the proxy settings. How can I do this with the qdrant client?

**Comment by KlausSchaefers** [comment]
When I disable TLS, I get the following error

```
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
	at qdrant.CrudTest.createCollection(CrudTest.java:34)
	at qdrant.CrudTest.testCrud(CrudTest.java:22)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:6334
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Anush008** [comment]
The above error suggests Qdrant gRPC is not accessible at `localhost:6334`.

**Comment by Anush008** [comment]
Can you try
```
docker run -p 6333:6333 -p 6334:6334 qdrant/qdrant
```

Followed by 
```
curl http://localhost:6333/
```

**Comment by KlausSchaefers** [comment]
I get some HTML error from our proxy service.

**Comment by KlausSchaefers** [comment]
So I need an option to overwrite the proxy settings. In python for instance we manually overwrite them 
```py
      res = requests.post(
            url, 
            headers=self.get_header(),
            json=req,
            proxies={
            "http": "",
            "https": ""
        })
```

**Comment by Anush008** [comment]
You can try constructing a `ManagedChannel` instance explicitly with the proxy instead.
As mentioned in https://github.com/qdrant/java-client?tab=readme-ov-file#creating-a-client.

**Comment by KlausSchaefers** [comment]
Hi, the workaround is in setting the `no_proxy` ENV variable and include also localhost.
